---
log_level: "20" # 20 is info, 10 is debug, 5 is trace
nfvcl:
  port: "5002"
  ip: "0.0.0.0"
  authentication: False
  workers: 4
mongodb:
  host: "mongo"
  port: "27017"
  db: "nfvcl"
redis:
  host: "redis"
  port: "6379"
